import { useState } from "react";
import {
  downloadSimulationReport,
  type ReportFormat,
  type ReportWindow,
} from "@/entities/reports/api/reportsApi";
import { useSimulationReport } from "@/entities/reports/api/useSimulationReport";
import { Button } from "@/shared/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/shared/ui/card";
import { EmptyState, SimulationOnlyNotice } from "@/shared/ui/industrial-states";
import { KpiCard } from "@/shared/ui/kpi-card";
import { PageShell } from "@/shared/ui/page-shell";
import { PanelShell } from "@/shared/ui/panel-shell";
import { StatusBadge } from "@/shared/ui/status-badge";

const reportWindows: ReportWindow[] = ["15m", "1h", "6h", "24h"];

export function ReportsPage() {
  const [windowValue, setWindowValue] = useState<ReportWindow>("1h");
  const [downloadError, setDownloadError] = useState<string | null>(null);
  const reportQuery = useSimulationReport(windowValue);
  const report = reportQuery.report;

  const handleDownload = async (format: ReportFormat) => {
    setDownloadError(null);
    try {
      await downloadSimulationReport(windowValue, format);
    } catch (error) {
      setDownloadError(error instanceof Error ? error.message : "Report download failed");
    }
  };

  return (
    <PageShell data-testid="reports-page">
      <section className="grid gap-6 xl:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)]">
        <PanelShell
          title="Simulation Reports"
          subtitle="JSON and CSV exports for synthetic simulator data. Not regulatory reporting."
          eyebrow="Report builder"
        >
          <div className="space-y-5">
            <SimulationOnlyNotice badgeLabel="Simulation-only report" />

            <label className="block space-y-2">
              <span className="text-sm font-medium text-foreground">Time window</span>
              <select
                className="w-full rounded-2xl border border-border bg-background px-4 py-3 text-sm text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                value={windowValue}
                onChange={(event) => setWindowValue(event.target.value as ReportWindow)}
                data-testid="reports-window-select"
              >
                {reportWindows.map((option) => (
                  <option key={option} value={option}>
                    {option}
                  </option>
                ))}
              </select>
            </label>

            <div className="grid gap-3 sm:grid-cols-2">
              <Button
                type="button"
                onClick={() => reportQuery.refresh()}
                data-testid="reports-generate-button"
              >
                Generate preview
              </Button>
              <Button
                type="button"
                variant="outline"
                onClick={() => handleDownload("json")}
                data-testid="reports-download-json"
              >
                Download JSON
              </Button>
              <Button
                type="button"
                variant="outline"
                onClick={() => handleDownload("csv")}
                data-testid="reports-download-csv"
              >
                Download CSV
              </Button>
              <Button
                type="button"
                variant="outline"
                onClick={() => handleDownload("pdf")}
                data-testid="reports-download-pdf"
              >
                Download PDF
              </Button>
            </div>

            {downloadError ? (
              <p
                className="rounded-2xl border border-danger/25 bg-danger/10 p-3 text-sm text-danger"
                role="alert"
              >
                {downloadError}
              </p>
            ) : null}
          </div>
        </PanelShell>

        <Card data-testid="reports-preview-card">
          <CardHeader>
            <div className="flex flex-wrap items-center justify-between gap-3">
              <CardTitle>Report Preview</CardTitle>
              <StatusBadge
                tone={
                  reportQuery.state === "connected"
                    ? "connected"
                    : reportQuery.state === "loading"
                      ? "degraded"
                      : "disabled"
                }
                value={reportQuery.state}
              >
                {reportQuery.state}
              </StatusBadge>
            </div>
            <CardDescription>
              Generated by the current demo RBAC session through the API gateway.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            {reportQuery.state === "loading" && !report ? (
              <p className="text-sm text-muted-foreground">
                Generating simulation-only report preview...
              </p>
            ) : report ? (
              <>
                <div className="grid gap-3 md:grid-cols-2">
                  <ReportMetric label="Report ID" value={report.reportId} mask />
                  <ReportMetric label="Window" value={report.timeWindow} />
                  <ReportMetric
                    label="Generated by"
                    value={`${report.generatedBy.displayName} / ${report.generatedBy.role}`}
                  />
                  <ReportMetric label="Data source" value={report.dataSources.history} />
                  <ReportMetric
                    label="System"
                    value={`${report.system.mode} / ${report.system.health}`}
                  />
                  <ReportMetric label="Scenario" value={report.system.activeScenario} />
                  <ReportMetric label="Control mode" value={report.control.mode} />
                  <ReportMetric label="PID" value={report.pid.status} />
                  <ReportMetric label="Historian" value={report.historian.status} />
                  <ReportMetric label="MQTT" value={report.mqtt.status} />
                  <ReportMetric label="Commands" value={String(report.commands.total)} mask />
                  <ReportMetric label="Events" value={String(report.events.total)} mask />
                  <ReportMetric label="Active alarms" value={String(report.alarms.active)} mask />
                  <ReportMetric label="Cleared alarms" value={String(report.alarms.cleared)} mask />
                </div>

                <div className="rounded-2xl border border-border/70 bg-surface-elevated/60 p-4">
                  <p className="text-sm font-medium text-foreground">Telemetry statistics</p>
                  <div className="mt-3 grid gap-2">
                    {report.telemetryStats.length === 0 ? (
                      <EmptyState
                        title="No historian samples"
                        message="No synthetic telemetry samples were available for this report window."
                      />
                    ) : (
                      report.telemetryStats.map((stat) => (
                        <div
                          key={stat.tag}
                          className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-background/50 px-3 py-2 text-sm"
                        >
                          <span className="font-mono text-muted-foreground">{stat.tag}</span>
                          <span className="text-foreground" data-visual-mask>
                            avg {stat.avg.toFixed(2)} {stat.unit}
                          </span>
                        </div>
                      ))
                    )}
                  </div>
                </div>
              </>
            ) : (
              <EmptyState
                title="Report preview unavailable"
                message="Refresh the simulation-only preview when the API is reachable."
              />
            )}
          </CardContent>
        </Card>
      </section>
    </PageShell>
  );
}

function ReportMetric({
  label,
  value,
  mask = false,
}: {
  label: string;
  value: string;
  mask?: boolean;
}) {
  return (
    <KpiCard
      label={label}
      value={value}
      className="p-3"
      mask={mask}
      formatValue={label !== "Report ID"}
    />
  );
}
