import { useState } from "react";
import {
  downloadSimulationReport,
  type ReportWindow,
} from "@/entities/reports/api/reportsApi";
import { useSimulationReport } from "@/entities/reports/api/useSimulationReport";
import { Badge } from "@/shared/ui/badge";
import { Button } from "@/shared/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/shared/ui/card";
import { PageShell } from "@/shared/ui/page-shell";

const reportWindows: ReportWindow[] = ["15m", "1h", "6h", "24h"];

export function ReportsPage() {
  const [windowValue, setWindowValue] = useState<ReportWindow>("1h");
  const [downloadError, setDownloadError] = useState<string | null>(null);
  const reportQuery = useSimulationReport(windowValue);
  const report = reportQuery.report;

  const handleDownload = async (format: "json" | "csv") => {
    setDownloadError(null);
    try {
      await downloadSimulationReport(windowValue, format);
    } catch (error) {
      setDownloadError(error instanceof Error ? error.message : "Report download failed");
    }
  };

  return (
    <PageShell data-testid="reports-page">
      <section className="grid gap-6 xl:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)]">
        <Card>
          <CardHeader>
            <CardTitle>Simulation Reports</CardTitle>
            <CardDescription>
              JSON and CSV exports for synthetic simulator data. Not regulatory reporting.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-5">
            <div className="rounded-2xl border border-warning/25 bg-warning/10 p-4">
              <Badge variant="warning">Simulation-only report</Badge>
              <p className="mt-3 text-sm leading-6 text-muted-foreground">
                Reports summarize synthetic telemetry, commands, alarms, events, historian, MQTT,
                and PID status for demo use only. They are not production audit records or nuclear
                compliance reports.
              </p>
            </div>

            <label className="block space-y-2">
              <span className="text-sm font-medium text-foreground">Time window</span>
              <select
                className="w-full rounded-2xl border border-border bg-background px-4 py-3 text-sm text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                value={windowValue}
                onChange={(event) => setWindowValue(event.target.value as ReportWindow)}
                data-testid="reports-window-select"
              >
                {reportWindows.map((option) => (
                  <option key={option} value={option}>
                    {option}
                  </option>
                ))}
              </select>
            </label>

            <div className="grid gap-3 sm:grid-cols-2">
              <Button type="button" onClick={() => reportQuery.refresh()} data-testid="reports-generate-button">
                Generate preview
              </Button>
              <Button type="button" variant="outline" onClick={() => handleDownload("json")} data-testid="reports-download-json">
                Download JSON
              </Button>
              <Button type="button" variant="outline" onClick={() => handleDownload("csv")} data-testid="reports-download-csv">
                Download CSV
              </Button>
            </div>

            {downloadError ? (
              <p className="rounded-2xl border border-danger/25 bg-danger/10 p-3 text-sm text-danger" role="alert">
                {downloadError}
              </p>
            ) : null}
          </CardContent>
        </Card>

        <Card data-testid="reports-preview-card">
          <CardHeader>
            <div className="flex flex-wrap items-center justify-between gap-3">
              <CardTitle>Report Preview</CardTitle>
              <Badge variant={reportQuery.state === "connected" ? "success" : reportQuery.state === "loading" ? "warning" : "offline"}>
                {reportQuery.state}
              </Badge>
            </div>
            <CardDescription>
              Generated by the current demo RBAC session through the API gateway.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            {reportQuery.state === "loading" && !report ? (
              <p className="text-sm text-muted-foreground">Generating simulation-only report preview...</p>
            ) : report ? (
              <>
                <div className="grid gap-3 md:grid-cols-2">
                  <ReportMetric label="Report ID" value={report.reportId} mask />
                  <ReportMetric label="Window" value={report.timeWindow} />
                  <ReportMetric label="Generated by" value={`${report.generatedBy.displayName} / ${report.generatedBy.role}`} />
                  <ReportMetric label="Data source" value={report.dataSources.history} />
                  <ReportMetric label="System" value={`${report.system.mode} / ${report.system.health}`} />
                  <ReportMetric label="Scenario" value={report.system.activeScenario} />
                  <ReportMetric label="Control mode" value={report.control.mode} />
                  <ReportMetric label="PID" value={report.pid.status} />
                  <ReportMetric label="Historian" value={report.historian.status} />
                  <ReportMetric label="MQTT" value={report.mqtt.status} />
                  <ReportMetric label="Commands" value={String(report.commands.total)} mask />
                  <ReportMetric label="Events" value={String(report.events.total)} mask />
                  <ReportMetric label="Active alarms" value={String(report.alarms.active)} mask />
                  <ReportMetric label="Cleared alarms" value={String(report.alarms.cleared)} mask />
                </div>

                <div className="rounded-2xl border border-border/70 bg-surface-elevated/60 p-4">
                  <p className="text-sm font-medium text-foreground">Telemetry statistics</p>
                  <div className="mt-3 grid gap-2">
                    {report.telemetryStats.length === 0 ? (
                      <p className="text-sm text-muted-foreground">No historian samples were available for this window.</p>
                    ) : (
                      report.telemetryStats.map((stat) => (
                        <div key={stat.tag} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-background/50 px-3 py-2 text-sm">
                          <span className="font-mono text-muted-foreground">{stat.tag}</span>
                          <span className="text-foreground" data-visual-mask>
                            avg {stat.avg.toFixed(2)} {stat.unit}
                          </span>
                        </div>
                      ))
                    )}
                  </div>
                </div>
              </>
            ) : (
              <p className="text-sm text-muted-foreground">Report preview unavailable.</p>
            )}
          </CardContent>
        </Card>
      </section>
    </PageShell>
  );
}

function ReportMetric({ label, value, mask = false }: { label: string; value: string; mask?: boolean }) {
  return (
    <div className="min-w-0 rounded-2xl border border-border/70 bg-surface-elevated/60 p-4">
      <p className="text-xs text-muted-foreground">{label}</p>
      <p className="mt-1 break-words text-sm font-semibold text-foreground" data-visual-mask={mask ? true : undefined}>{value}</p>
    </div>
  );
}
