import type { Equipment } from "@/entities/equipment/model/types";

export const mockEquipment: Equipment[] = [
  {
    id: "tank-101",
    tag: "T-101",
    name: "Buffer Tank",
    type: "tank",
    status: "mock",
    location: "Unit-001 / Thermal Loop",
    description: "Simplified tank model for loop inventory and level monitoring.",
    telemetryTags: ["LT-101"],
  },
  {
    id: "pump-101",
    tag: "P-101",
    name: "Primary Circulation Pump",
    type: "pump",
    status: "offline",
    location: "Unit-001 / Pump Bay",
    description: "State-machine placeholder for future pump simulator.",
    telemetryTags: ["P-101.STATE", "FT-101"],
  },
  {
    id: "valve-101",
    tag: "V-101",
    name: "Control Valve",
    type: "valve",
    status: "warning",
    location: "Unit-001 / Valve Station",
    description: "Future command target for manual and PID-driven positioning.",
    telemetryTags: ["V-101.POS"],
  },
  {
    id: "hx-101",
    tag: "HX-101",
    name: "Heat Exchanger",
    type: "heat-exchanger",
    status: "mock",
    location: "Unit-001 / Thermal Loop",
    description: "Simplified heat transfer equipment for process visualization.",
    telemetryTags: ["TT-101", "FT-101"],
  },
  {
    id: "tic-101",
    tag: "TIC-101",
    name: "Temperature PID Controller",
    type: "controller",
    status: "normal",
    location: "Unit-001 / Control Layer",
    description: "Placeholder controller for setpoint-driven valve commands.",
    telemetryTags: ["TT-101", "V-101.POS"],
  },
];
