package simulation

import (
	"bytes"
	"fmt"
	"strconv"
	"strings"
	"time"
	"unicode"
)

func simulationReportPDF(report SimulationReport, options ReportOptions) ([]byte, error) {
	lines := []string{
		"SMR Digital Twin Simulation Report",
		"Simulation-only engineering report generated from synthetic demo telemetry.",
		"Not a regulatory, safety, compliance, or production operations report.",
		"",
		"Template: " + report.Template,
		"",
	}
	if reportHasSection(options, "metadata") {
		lines = append(lines,
			"Report ID: "+report.ReportID,
			"Generated at: "+report.GeneratedAt.Format(time.RFC3339),
			"Window: "+report.TimeWindow,
			"Generated by: "+report.GeneratedBy.DisplayName+" / "+report.GeneratedBy.Role,
			"Simulation only: "+strconv.FormatBool(report.SimulationOnly),
			"",
		)
	}
	if reportHasSection(options, "safetyDisclaimer") || !options.IncludeDisclaimers {
		lines = append(lines,
			"Disclaimer: "+report.Disclaimer,
			"",
		)
	}
	if reportHasSection(options, "systemSummary") {
		lines = append(lines,
			"System",
			"Mode: "+report.System.Mode,
			"Health: "+report.System.Health,
			"Running: "+strconv.FormatBool(report.System.Running),
			"",
		)
	}
	if reportHasSection(options, "scenarioSummary") {
		lines = append(lines,
			"Scenario",
			"Active scenario: "+report.System.ActiveScenario,
			"",
		)
	}
	if reportHasSection(options, "historianSummary") || reportHasSection(options, "mqttSummary") {
		lines = append(lines, "Integrations")
		if reportHasSection(options, "historianSummary") {
			lines = append(lines, "Historian: "+report.Historian.Status+" ("+report.DataSources.History+")")
		}
		if reportHasSection(options, "mqttSummary") {
			lines = append(lines, "MQTT: "+report.MQTT.Status)
		}
		lines = append(lines, "Data degraded: "+strconv.FormatBool(report.DataSources.Degraded), "")
	}
	if reportHasSection(options, "pidSummary") {
		lines = append(lines,
			"Control and PID",
			"Control mode: "+report.Control.Mode,
			"Control authority: "+report.Control.Authority,
			"PID status: "+report.PID.Status,
			fmt.Sprintf("PID setpoint/output/error: %.2f C / %.2f %% / %.2f C", report.PID.Setpoint, report.PID.Output, report.PID.Error),
			"",
		)
	}
	if reportHasSection(options, "processSummary") {
		lines = append(lines,
			"Latest process snapshot",
			fmt.Sprintf("TT-101 loop temperature: %.2f C", report.LatestTelemetry.LoopTemperatureC),
			fmt.Sprintf("PT-101 loop pressure: %.2f MPa", report.LatestTelemetry.LoopPressureMPa),
			fmt.Sprintf("FT-101 loop flow: %.2f kg/s", report.LatestTelemetry.LoopFlowKGS),
			fmt.Sprintf("V-101 position: %.2f %%", report.LatestTelemetry.ValvePositionPct),
			"P-101 state: "+report.LatestTelemetry.PumpState,
			"",
		)
	}
	if reportHasSection(options, "commandSummary") || reportHasSection(options, "eventSummary") || reportHasSection(options, "alarmSummary") {
		lines = append(lines, "Activity summary")
		if reportHasSection(options, "commandSummary") {
			lines = append(lines, "Commands total: "+strconv.Itoa(report.Commands.Total))
		}
		if reportHasSection(options, "eventSummary") {
			lines = append(lines, "Events total: "+strconv.Itoa(report.Events.Total))
		}
		if reportHasSection(options, "alarmSummary") {
			lines = append(lines,
				"Active alarms: "+strconv.Itoa(report.Alarms.Active),
				"Acknowledged alarms: "+strconv.Itoa(report.Alarms.Acknowledged),
				"Cleared alarms: "+strconv.Itoa(report.Alarms.Cleared),
			)
		}
		lines = append(lines, "")
	}
	if reportHasSection(options, "trendStatistics") {
		lines = append(lines, "Telemetry min / avg / max")
		for _, stat := range report.TelemetryStats {
			lines = append(lines, fmt.Sprintf("%s %s: %.2f / %.2f / %.2f %s (%d samples, %s)", stat.Tag, stat.Label, stat.Min, stat.Avg, stat.Max, stat.Unit, stat.Count, stat.Source))
		}
		if len(report.TelemetryStats) == 0 {
			lines = append(lines, "No historian telemetry samples were available for this window.")
		}
	}

	return renderSimplePDF(lines), nil
}

func renderSimplePDF(lines []string) []byte {
	const linesPerPage = 43
	pages := chunkLines(lines, linesPerPage)
	if len(pages) == 0 {
		pages = [][]string{{""}}
	}

	objects := make([]string, 0, 3+len(pages)*2)
	objects = append(objects, `<< /Type /Catalog /Pages 2 0 R >>`)

	kids := make([]string, 0, len(pages))
	for i := range pages {
		kids = append(kids, fmt.Sprintf("%d 0 R", 4+i*2))
	}
	objects = append(objects, fmt.Sprintf(`<< /Type /Pages /Kids [%s] /Count %d >>`, strings.Join(kids, " "), len(pages)))
	objects = append(objects, `<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`)

	for i, page := range pages {
		pageObject := 4 + i*2
		contentObject := pageObject + 1
		objects = append(objects, fmt.Sprintf(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents %d 0 R >>`, contentObject))
		stream := pdfTextStream(page)
		objects = append(objects, fmt.Sprintf("<< /Length %d >>\nstream\n%s\nendstream", len(stream), stream))
	}

	buffer := &bytes.Buffer{}
	buffer.WriteString("%PDF-1.4\n")
	offsets := make([]int, len(objects)+1)
	for i, object := range objects {
		objectNumber := i + 1
		offsets[objectNumber] = buffer.Len()
		buffer.WriteString(fmt.Sprintf("%d 0 obj\n%s\nendobj\n", objectNumber, object))
	}
	xrefOffset := buffer.Len()
	buffer.WriteString(fmt.Sprintf("xref\n0 %d\n", len(objects)+1))
	buffer.WriteString("0000000000 65535 f \n")
	for i := 1; i <= len(objects); i++ {
		buffer.WriteString(fmt.Sprintf("%010d 00000 n \n", offsets[i]))
	}
	buffer.WriteString(fmt.Sprintf("trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n", len(objects)+1, xrefOffset))
	return buffer.Bytes()
}

func chunkLines(lines []string, chunkSize int) [][]string {
	chunks := [][]string{}
	for start := 0; start < len(lines); start += chunkSize {
		end := start + chunkSize
		if end > len(lines) {
			end = len(lines)
		}
		chunks = append(chunks, lines[start:end])
	}
	return chunks
}

func pdfTextStream(lines []string) string {
	stream := &strings.Builder{}
	stream.WriteString("BT\n/F1 10 Tf\n72 744 Td\n")
	for i, line := range lines {
		if i == 0 {
			stream.WriteString("/F1 16 Tf\n")
		} else if i == 1 {
			stream.WriteString("/F1 10 Tf\n")
		}
		stream.WriteString("(")
		stream.WriteString(escapePDFText(truncatePDFLine(line)))
		stream.WriteString(") Tj\n0 -16 Td\n")
	}
	stream.WriteString("ET")
	return stream.String()
}

func truncatePDFLine(line string) string {
	const maxLineLength = 110
	runes := []rune(line)
	if len(runes) <= maxLineLength {
		return line
	}
	return string(runes[:maxLineLength-3]) + "..."
}

func escapePDFText(value string) string {
	value = normalizePDFText(value)
	value = strings.ReplaceAll(value, `\`, `\\`)
	value = strings.ReplaceAll(value, "(", `\(`)
	value = strings.ReplaceAll(value, ")", `\)`)
	value = strings.ReplaceAll(value, "\r", " ")
	value = strings.ReplaceAll(value, "\n", " ")
	return value
}

func normalizePDFText(value string) string {
	builder := strings.Builder{}
	for _, r := range value {
		switch {
		case r == '\r' || r == '\n' || r == '\t':
			builder.WriteRune(' ')
		case r >= 32 && r <= 126:
			builder.WriteRune(r)
		case unicode.IsSpace(r):
			builder.WriteRune(' ')
		default:
			builder.WriteRune('?')
		}
	}
	return builder.String()
}
